apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microfrontend.fullname" . }}
  labels:
    {{- include "microfrontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microfrontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "microfrontend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "microfrontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8005
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: API
              value: {{ .Values.remote.api }}
            - name: RANCHER_ENV
              value: {{ .Values.remote.rancherEnv }}
            - name: ROUTER_BASE
              value: /api/v1/namespaces/{{ .Release.Namespace }}/services/http:{{ include "microfrontend.fullname" . }}:{{ .Values.service.port }}/proxy{{ .Values.remote.routerBase }}
            - name: RESOURCE_BASE
              value: {{ .Values.remote.resourceBase }}
        - name: {{ .Chart.Name }}-proxy
          args:
            - nginx
            - '-g'
            - daemon off;
            - '-c'
            - /nginx/nginx.conf
          image: rancher/mirrored-library-nginx:1.24.0-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: nginx-http
              protocol: TCP
          resources: {}
          securityContext:
            runAsGroup: 101
            runAsUser: 101
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /nginx
              name: microfrontend-nginx
            - mountPath: /var/cache/nginx
              name: nginx-home
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
