apiVersion: v1
kind: ConfigMap
metadata:
  name: microfrontend-nginx-proxy-config
  labels:
    {{- include "microfrontend.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    worker_processes      auto;
    error_log             /dev/stdout warn;
    pid                   /var/cache/nginx/nginx.pid;

    events {
       worker_connections 1024;
    }

    http {
      include       /etc/nginx/mime.types;
      log_format    main '[$time_local - $status] $remote_addr - $remote_user $request ($http_referer)';

      proxy_connect_timeout       10;
      proxy_read_timeout          180;
      proxy_send_timeout          5;
      proxy_buffering             off;
      proxy_cache_path            /var/cache/nginx/cache levels=1:2 keys_zone=my_zone:100m inactive=1d max_size=10g;

      server {
        listen          8080;
        access_log      off;

        gzip            on;
        gzip_min_length 1k;
        gzip_comp_level 2;
        gzip_types      text/plain application/javascript application/x-javascript text/css application/xml text/javascript image/jpeg image/gif image/png;
        gzip_vary       on;
        gzip_disable    "MSIE [1-6]\.";

        proxy_set_header Host $host;

        location / {
          
          proxy_pass     https://localhost:8005/;

          sub_filter_once off;

          sub_filter '"appSubUrl":""' '"appSubUrl":"/api/v1/namespaces/{{ .Release.Namespace }}/services/http:{{ include "microfrontend.fullname" . }}:{{ .Values.service.port }}/proxy"';

        }
      }
    }
