apiVersion: v1
kind: Service
metadata:
  name: {{ include "microfrontend.fullname" . }}
  labels:
    {{- include "microfrontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: microfrontend-http
  selector:
    {{- include "microfrontend.selectorLabels" . | nindent 4 }}
