name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  build-and-push-remote:
    uses: ./.github/workflows/docker-push.yaml
    with:
      image-name: remote
      tag-name: ${{ github.ref_name }}
      working-directory: src
    permissions:
      contents: read
      packages: write
